# Backbone
backbone: resnet50

# Transfer loss related
transfer_loss_weight: 10.0
transfer_loss: coral

# Optimizer related
lr: 3e-3
weight_decay: 5e-4
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75
momentum: 0.9

# Training related
n_iter_per_epoch: 500
n_epoch: 50
early_stop: 5
batch_size: 32
epoch_based_training: true
use_bottleneck: true

# Data
data_dir: /content/24-25_CE301_kittichalermroj_yodsakit/Office-31
src_domain: dslr
tgt_domain: webcam

# Others
seed: 1
num_workers: 3
