data_dir: /content/ProjectTest/Office-31
src_domain: amazon
tgt_domain: webcam
backbone: resnet50
use_bottleneck: true
transfer_loss: coral
n_epoch: 50
batch_size: 32
lr: 0.001
lr_scheduler: true
early_stop: 5
epoch_based_training: true