# Backbone
backbone: resnet50

# Transfer loss related
transfer_loss_weight: 0.5
transfer_loss: lmmd

# Optimizer related
lr: 0.01
weight_decay: 5e-4
momentum: 0.9
lr_scheduler: True
lr_gamma: 0.0003
lr_decay: 0.75

# Training related
n_iter_per_epoch: 500
n_epoch: 50
use_bottleneck: True
epoch_based_training: True
batch_size: 32
early_stop: 5

# Data
data_dir: /content/24-25_CE301_kittichalermroj_yodsakit/Office-31
src_domain: dslr
tgt_domain: webcam

# Others
seed: 1
num_workers: 3
